#! /bin/zsh --no-rcs --err-exit --null-glob
source /etc/profile

git config --get remote.origin.url | read
: ${GITHUB_REPOSITORY:=$REPLY:h:t/$REPLY:t:r}

HOMEBREW_NO_AUTO_UPDATE=true

if (($+GITHUB_ACTIONS)) then
  brew test-bot --only-cleanup-before
  brew test-bot --only-setup
  brew test-bot --only-tap-syntax
  if ([[ $GITHUB_EVENT_NAME = pull_request ]]) brew test-bot --only-formulae
  set \*
fi

if (($#)) then print -l **/$~^@:t:r.rb
else git diff --staged --name-only --diff-filter ACM | grep '\.rb$'
fi | while read rb
do
  token=$GITHUB_REPOSITORY/$rb:t:r
  head -n 1 $rb | read first_line

  case $first_line in
    class*Formula)
      if ([[ $GITHUB_EVENT_NAME != pull_request ]]) &&
      brew test-bot --skip-setup --fail-fast --only-formulae $token --skip-recursive-dependents;;

    cask*do)
      brew style $token
      if ((!$+GITHUB_ACTIONS)) brew audit --cask --appcast $token
      brew audit --cask --strict ${GITHUB_ACTIONS+--online} $token ${@:2};;

    *) brew style $rb
  esac
done
