#! /bin/zsh -f

git diff --cached --name-only --diff-filter=ACM | grep .rb$ |
while read i
do case $i in
  Formula*) brew audit --strict --online $i:A;; #--new-formula
  Cask*)
    brew cask audit $i:A && #--download
    brew cask style $i:A;; #--fix
esac
done
